### ISSUE TITLE
How advanced is this project and would it be already sufficient for a minimal VOIP application?

### ISSUE THREAD

**Issue by RaphaelMaschinsen** [mumble-voip/libmumble#5]
I'm working on a project involving VOIP Communication on Raspberry Pi Zeros within a local Network. I would like to write the code in C++. Reading this project's description in the "readme.md" branch sounds very promising and it appears like this project could be a perfect fit.

I was able to build the examples but I'm not sure if it is worth going any deeper for now since I'm not sure how advanced this project is. Would the state of this project be sufficient for a minimal VOIP-Application involving a few participants within a single channel? I don't mind the lack of documentation since the code appears to be very readable and clean.

Thanks for the promising project.

**Comment by Krzmbrzl** [comment]
Afaik the code as-is should be fine for your purposes. 
Note however that the API is likely to change as there is currently a review ongoing (it has turned out to take quite a while though) so if you adopt the code in its current state you will probably have to make adjustments when you want to upgrade to a future release of this lib.

**Comment by RaphaelMaschinsen** [comment]
That's no problem at all! Glad to hear this and I will get deeper into the code then. Thanks for the reply and I'm looking forward to see where this project is going!

**Comment by davidebeatrici** [comment]
Thank you very much for your interest and positive comments!

Feel free to join [#mumble-dev:matrix.org](https://matrix.to/#/#mumble-dev:matrix.org), we can discuss about the library there.
